### ISSUE TITLE
Dont post the comment if no issues found

### ISSUE THREAD

**Issue by mvehar-preskok** [Louis-7/ai-code-review#57]

**Comment by Louis-7** [comment]
@mvehar-preskok can you give me an example of a comment which not include any issue in it? Based on my experience, chatGPT will give you suggestions even if your input is Hello World😅

**Comment by mvehar-preskok** [comment]
We get a comment: ```No issues found.```

**Comment by Louis-7** [comment]
Can you share your prompt? I want to create a file to collect useful code review prompts.

About skip review comments, I can add an option to accept a string array so that you can specify which comment you want the AI to skip.

**Comment by mvehar-preskok** [comment]
If we can skip the above mention text (via config array), it would be avesome

**Comment by Louis-7** [comment]
A new option has been added.

BTW, it would be awesome if you could share your prompt.
